name: ControlBP
main: ControlBP\ControlBP
version: 1.0.0
author: ByPaps
api: [3.0.0, 4.0.0]
load: POSTWORLD
commands:
 ct:
  permission: ct.commnd.use
  description: Control from afar
  usage: /ct third >Player<
 ct blow:
  permission: ct.command.blow
  description: Hit from afar
permissions:
 ct:
    default: op
    description:
   ct.command.true:
    default: op
    description: 
   ct.command.false:
    default: op
    description: 
   ct.command.place:
    default: op
    description: 
   ct.command.blow:
    default: op
    description: 
